name: flutter_dark_mvp
description: Dark-themed personal manager (Todos + Calendar + Expenses)
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  google_mlkit_text_recognition: ^0.13.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  uuid: ^4.5.1
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
